name: family_pro_health
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  dio: ^5.0.1
  json_annotation: ^4.8.0
  get_storage: ^2.1.1
  objectbox: ^1.7.2
  flutter_blue: ^0.8.0
  intl: ^0.18.0
  connectivity_plus: ^3.0.3
  path_provider: ^2.0.13
  provider: ^6.0.5
  path: ^1.8.2
  objectbox_flutter_libs: ^1.7.2
  async: ^2.10.0
  flutter_svg: ^2.0.4
  package_info_plus: ^3.0.3
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^5.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  objectbox_generator: ^1.7.2

objectbox:
  output_dir:
    lib: database
    test: database

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svgs/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
